import { describe, expect, it, vi } from 'vitest'
import { SdkSessionSettlement } from '../src/session-settlement.ts'

function activity(wait: (id: string) => Promise<void> = async () => {}) {
  const settled = vi.fn<(id: string, error?: Error) => void>()
  const tracker = new SdkSessionSettlement(wait, settled)
  return { tracker, settled }
}

describe('SDK session-tree settlement', () => {
  it('publishes once after a native join and permits a later interval', async () => {
    const { tracker, settled } = activity()
    tracker.status('root', 'idle')
    tracker.begin('root')
    tracker.inbox('root', 1, 0)
    tracker.status('root', 'running')
    tracker.inbox('root', 0, 1)
    tracker.status('root', 'idle')
    tracker.status('root', 'idle')
    await tracker.drain()
    expect(settled.mock.calls).toEqual([['root', undefined]])
    tracker.begin('root')
    tracker.status('root', 'idle')
    await tracker.drain()
    expect(settled).toHaveBeenCalledTimes(2)
  })

  it('keeps the interval open through descendant work and parent continuation', async () => {
    const gate = Promise.withResolvers<undefined>()
    const wait = vi.fn(() => gate.promise)
    const { tracker, settled } = activity(wait)
    tracker.begin('root')
    tracker.status('root', 'idle')
    await vi.waitFor(() => { expect(wait).toHaveBeenCalledWith('root') })
    expect(settled).not.toHaveBeenCalled()
    tracker.inbox('root', 1, 0)
    tracker.status('root', 'running')
    tracker.inbox('root', 0, 1)
    tracker.status('root', 'idle')
    gate.resolve(undefined)
    await tracker.drain()
    expect(settled.mock.calls).toEqual([['root', undefined]])
    expect(wait).toHaveBeenCalledTimes(1)
  })

  it('rechecks a new prompt admitted while the earlier native wait completes', async () => {
    const oldWait = Promise.withResolvers<undefined>()
    const newWait = Promise.withResolvers<undefined>()
    const wait = vi.fn().mockReturnValueOnce(oldWait.promise).mockReturnValueOnce(newWait.promise)
    const { tracker, settled } = activity(wait)
    tracker.begin('root')
    tracker.status('root', 'idle')
    await vi.waitFor(() => { expect(wait).toHaveBeenCalledTimes(1) })
    tracker.begin('root')
    tracker.status('root', 'idle')
    oldWait.resolve(undefined)
    await vi.waitFor(() => { expect(wait).toHaveBeenCalledTimes(2) })
    expect(settled).not.toHaveBeenCalled()
    newWait.resolve(undefined)
    await tracker.drain()
    expect(settled).toHaveBeenCalledTimes(1)
  })

  it('does not block an unrelated root on another root’s native descendants', async () => {
    const gate = Promise.withResolvers<undefined>()
    const { tracker, settled } = activity(id => id === 'a' ? gate.promise : Promise.resolve(undefined))
    tracker.begin('a')
    tracker.begin('b')
    tracker.status('a', 'idle')
    tracker.status('b', 'idle')
    await vi.waitFor(() => { expect(settled.mock.calls).toEqual([['b', undefined]]) })
    gate.resolve(undefined)
    await tracker.drain()
    expect(settled.mock.calls).toEqual([['b', undefined], ['a', undefined]])
  })

  it('retains ancestry without treating a parked child as running work', async () => {
    const { tracker, settled } = activity()
    tracker.linkChild('middle', 'root')
    tracker.linkChild('leaf', 'middle')
    tracker.linkChild('a', 'b')
    tracker.linkChild('b', 'a')
    expect(tracker.belongsTo('leaf', 'root')).toBe(true)
    expect(tracker.belongsTo('a', 'root')).toBe(false)
    tracker.begin('root')
    tracker.status('root', 'idle')
    await tracker.drain()
    expect(settled).toHaveBeenCalledTimes(1)
  })

  it('waits for queued next-turn input and handles cancellation without negative counts', async () => {
    const wait = vi.fn(async () => {})
    const { tracker, settled } = activity(wait)
    tracker.inbox('unowned', 1, 0)
    tracker.begin('root')
    tracker.inbox('root', 2, 0)
    tracker.status('root', 'idle')
    expect(wait).not.toHaveBeenCalled()
    tracker.inbox('root', 0, 3)
    await tracker.drain()
    expect(settled).toHaveBeenCalledTimes(1)
  })

  it('reports native completion failure instead of silently hanging a client', async () => {
    const error = new Error('terminal append failed')
    const { tracker, settled } = activity(async () => { throw error })
    tracker.begin('root')
    tracker.status('root', 'idle')
    await tracker.drain()
    expect(settled).toHaveBeenCalledWith('root', error)
  })

  it('joins outstanding waits after teardown without publishing a late completion', async () => {
    const gate = Promise.withResolvers<undefined>()
    const wait = vi.fn(() => gate.promise)
    const { tracker, settled } = activity(wait)
    tracker.begin('root')
    tracker.status('root', 'idle')
    await vi.waitFor(() => { expect(wait).toHaveBeenCalledTimes(1) })
    tracker.close()
    tracker.begin('later')
    tracker.linkChild('child', 'later')
    tracker.status('later', 'idle')
    tracker.inbox('later', 0, 1)
    gate.resolve(undefined)
    await tracker.drain()
    expect(settled).not.toHaveBeenCalled()
    expect(tracker.belongsTo('child', 'later')).toBe(false)
  })
})


it('releases the waiter task when the notification transport throws', async () => {
  const tracker = new SdkSessionSettlement(async () => {}, () => { throw new Error('transport closed') })
  tracker.begin('root')
  tracker.status('root', 'idle')
  await tracker.drain()
  tracker.close()
  await tracker.drain()
})
